/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Swift
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSALIR = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Untelslogo = new javax.swing.JLabel();
        TITULO2 = new javax.swing.JLabel();
        delimasur = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        vel = new javax.swing.JLabel();
        ang = new javax.swing.JLabel();
        grav = new javax.swing.JLabel();
        textVel = new javax.swing.JTextField();
        textAng = new javax.swing.JTextField();
        textGrav = new javax.swing.JTextField();
        textResultado = new javax.swing.JTextField();
        Resultadoboton = new javax.swing.JButton();
        ejercicio = new javax.swing.JLabel();
        EJERCICIO = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        imagMP = new javax.swing.JLabel();
        MRU = new javax.swing.JPanel();
        velmru = new javax.swing.JLabel();
        posicionmru = new javax.swing.JLabel();
        angmru = new javax.swing.JLabel();
        tiempomru = new javax.swing.JLabel();
        textVelomru = new javax.swing.JTextField();
        textPosicionmru = new javax.swing.JTextField();
        textAngmru = new javax.swing.JTextField();
        textTiempomru = new javax.swing.JTextField();
        Resultadoboton3 = new javax.swing.JButton();
        textResultado3 = new javax.swing.JTextField();
        mruv = new javax.swing.JPanel();
        angy = new javax.swing.JLabel();
        vely = new javax.swing.JLabel();
        gravy = new javax.swing.JLabel();
        tiempoy = new javax.swing.JLabel();
        textAngy = new javax.swing.JTextField();
        textvely = new javax.swing.JTextField();
        textGravy = new javax.swing.JTextField();
        textTiempoy = new javax.swing.JTextField();
        Resultadoboton2 = new javax.swing.JButton();
        textResultado2 = new javax.swing.JTextField();
        textingexercise = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSALIR.setBackground(new java.awt.Color(0, 0, 51));
        BotonSALIR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonSALIR.setForeground(new java.awt.Color(255, 255, 255));
        BotonSALIR.setText("SALIR");
        BotonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, 90, 30));

        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Titulo.setText("UNIVERSIDAD");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 20));

        Untelslogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/untels2.png"))); // NOI18N
        getContentPane().add(Untelslogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 70));

        TITULO2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TITULO2.setText("Nacional Tecnológica");
        getContentPane().add(TITULO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 30));

        delimasur.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delimasur.setText("DE LIMA SUR");
        getContentPane().add(delimasur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("\"MOVIMIENTO PARABOLICO\"\n");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tiempo en alcanzar su Hmax"));

        vel.setText("Velocidad inicial:");

        ang.setText("Sen del angulo:");

        grav.setText("Gravedad:");

        textResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResultadoActionPerformed(evt);
            }
        });

        Resultadoboton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Resultadoboton.setForeground(new java.awt.Color(0, 51, 204));
        Resultadoboton.setText("CALCULAR");
        Resultadoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadobotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grav)
                            .addComponent(Resultadoboton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textGrav, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textAng, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vel)
                        .addGap(41, 41, 41)
                        .addComponent(textVel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vel)
                    .addComponent(textVel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ang)
                    .addComponent(textAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grav)
                    .addComponent(textGrav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resultadoboton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 310, 240));

        ejercicio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ejercicio.setForeground(new java.awt.Color(255, 255, 0));
        ejercicio.setText("EJERCICIO DE APLICACION:");
        getContentPane().add(ejercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 360, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Se lanza un cuerpo con una velocidad \ninicial de 300m/s y con un ángulo de \ntiro de 60° con la horizontal. \nHallar la posición de su velocidad \ncuando t=10s después del disparo y el \ntiempo en que alcanza su Hmax.\n(Use g=10m/s^2).");
        EJERCICIO.setViewportView(jTextArea1);

        getContentPane().add(EJERCICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 340, 160));

        imagMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imagenmp.png"))); // NOI18N
        getContentPane().add(imagMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 310, 200));

        MRU.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para el MRU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 0, 51))); // NOI18N
        MRU.setForeground(new java.awt.Color(204, 0, 51));

        velmru.setText("Velocidad inicial (Vox):");

        posicionmru.setText("Posicion inicial (Xo):");

        angmru.setText("Cos del angulo:");

        tiempomru.setText("Tiempo:");

        textVelomru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textVelomruActionPerformed(evt);
            }
        });

        Resultadoboton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Resultadoboton3.setForeground(new java.awt.Color(0, 51, 204));
        Resultadoboton3.setText("CALCULAR");
        Resultadoboton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resultadoboton3ActionPerformed(evt);
            }
        });

        textResultado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResultado3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MRULayout = new javax.swing.GroupLayout(MRU);
        MRU.setLayout(MRULayout);
        MRULayout.setHorizontalGroup(
            MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MRULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MRULayout.createSequentialGroup()
                        .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicionmru)
                            .addComponent(velmru)
                            .addComponent(angmru)
                            .addComponent(tiempomru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTiempomru, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(textAngmru)
                            .addComponent(textVelomru)
                            .addComponent(textPosicionmru)))
                    .addGroup(MRULayout.createSequentialGroup()
                        .addComponent(Resultadoboton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(textResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        MRULayout.setVerticalGroup(
            MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MRULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPosicionmru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionmru))
                .addGap(18, 18, 18)
                .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(velmru)
                    .addComponent(textVelomru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angmru)
                    .addComponent(textAngmru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempomru)
                    .addComponent(textTiempomru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resultadoboton3)
                    .addComponent(textResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(MRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 250, 310));

        mruv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para el MRUV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 0, 51)))); // NOI18N

        angy.setText("Sen del angulo:");

        vely.setText("Velocidad incial (Voy): ");

        gravy.setText("Gravedad:");

        tiempoy.setText("Tiempo:");

        Resultadoboton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Resultadoboton2.setForeground(new java.awt.Color(0, 51, 204));
        Resultadoboton2.setText("CALCULAR");
        Resultadoboton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resultadoboton2ActionPerformed(evt);
            }
        });

        textResultado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResultado2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mruvLayout = new javax.swing.GroupLayout(mruv);
        mruv.setLayout(mruvLayout);
        mruvLayout.setHorizontalGroup(
            mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mruvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gravy)
                    .addComponent(tiempoy)
                    .addComponent(vely))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mruvLayout.createSequentialGroup()
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mruvLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Resultadoboton2))
                    .addGroup(mruvLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(angy)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mruvLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textAngy, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textTiempoy, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(textGravy)))
                            .addGroup(mruvLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textvely, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        mruvLayout.setVerticalGroup(
            mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mruvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vely)
                    .addComponent(textvely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angy)
                    .addComponent(textAngy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gravy)
                    .addComponent(textGravy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoy)
                    .addComponent(textTiempoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(mruvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resultadoboton2)
                    .addComponent(textResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(mruv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 270, 240));

        textingexercise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        textingexercise.setText("MRYU");
        getContentPane().add(textingexercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSALIRActionPerformed
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_BotonSALIRActionPerformed

    private void textResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResultadoActionPerformed

    private void ResultadobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadobotonActionPerformed
        // TODO add your handling code here:
        double vel, ang,sen, grav;
       
       double cambio =2;
       double resultado3= Math.sqrt(cambio);
      
        double b=0;
        vel = Double.parseDouble(textVel.getText());
        ang = Double.parseDouble(textAng.getText());
        grav = Double.parseDouble(textGrav.getText());
        
        
        b = Math.toRadians(ang);
        sen = Math.sin(b);
        
        resultado3 =(vel*sen)/grav;
      
        textResultado.setText(String.format("%.2f",resultado3));
    }//GEN-LAST:event_ResultadobotonActionPerformed

    private void textVelomruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textVelomruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textVelomruActionPerformed

    private void Resultadoboton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resultadoboton3ActionPerformed
        // TODO add your handling code here:
        double velmru, angmru,sen, tiempomru,posicionmru;
        double b=0;
        double cambio =2;
       double resultado3= Math.sqrt(cambio);
       
        velmru = Double.parseDouble(textVelomru.getText());
        angmru = Double.parseDouble(textAngmru.getText());
        tiempomru = Double.parseDouble(textTiempomru.getText());
        tiempomru = Double.parseDouble(textTiempomru.getText());
        posicionmru = Double.parseDouble(textPosicionmru.getText());
        
         b = Math.toRadians(angmru);
        sen = Math.cos(b);
        
        resultado3 = posicionmru + velmru*sen*tiempomru;
        
        textResultado3.setText(String.format("%.2f",resultado3));
    }//GEN-LAST:event_Resultadoboton3ActionPerformed

    private void textResultado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResultado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResultado3ActionPerformed

    private void Resultadoboton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resultadoboton2ActionPerformed
        // TODO add your handling code here:
        double vely, angy, tiempoy,gravy,sen;
        double b=0;
        double cambio =2;
        double resultado2= Math.sqrt(cambio);
        
        vely = Double.parseDouble(textvely.getText());
        angy = Double.parseDouble(textAngy.getText());
        gravy = Double.parseDouble(textGravy.getText());
        tiempoy = Double.parseDouble(textTiempoy.getText());
        
        
        b = Math.toRadians(angy);
        sen = Math.sin(b);
        
        resultado2 = vely*sen*tiempoy - 0.5*(gravy)*tiempoy*tiempoy;
        
        textResultado2.setText(String.format("%.2f",resultado2));
    }//GEN-LAST:event_Resultadoboton2ActionPerformed

    private void textResultado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResultado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResultado2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSALIR;
    private javax.swing.JScrollPane EJERCICIO;
    private javax.swing.JPanel MRU;
    private javax.swing.JButton Resultadoboton;
    private javax.swing.JButton Resultadoboton2;
    private javax.swing.JButton Resultadoboton3;
    private javax.swing.JLabel TITULO2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Untelslogo;
    private javax.swing.JLabel ang;
    private javax.swing.JLabel angmru;
    private javax.swing.JLabel angy;
    private javax.swing.JLabel delimasur;
    private javax.swing.JLabel ejercicio;
    private javax.swing.JLabel grav;
    private javax.swing.JLabel gravy;
    private javax.swing.JLabel imagMP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mruv;
    private javax.swing.JLabel posicionmru;
    private javax.swing.JTextField textAng;
    private javax.swing.JTextField textAngmru;
    private javax.swing.JTextField textAngy;
    private javax.swing.JTextField textGrav;
    private javax.swing.JTextField textGravy;
    private javax.swing.JTextField textPosicionmru;
    private javax.swing.JTextField textResultado;
    private javax.swing.JTextField textResultado2;
    private javax.swing.JTextField textResultado3;
    private javax.swing.JTextField textTiempomru;
    private javax.swing.JTextField textTiempoy;
    private javax.swing.JTextField textVel;
    private javax.swing.JTextField textVelomru;
    private javax.swing.JLabel textingexercise;
    private javax.swing.JTextField textvely;
    private javax.swing.JLabel tiempomru;
    private javax.swing.JLabel tiempoy;
    private javax.swing.JLabel vel;
    private javax.swing.JLabel velmru;
    private javax.swing.JLabel vely;
    // End of variables declaration//GEN-END:variables
}
